// <auto-generated />
using System;
using GoodHamburger.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513000730_SeedUsuarioAdmin")]
    partial class SeedUsuarioAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Itens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(1742),
                            Nome = "X Burger",
                            PrecoUnitario = 5.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(1745),
                            Nome = "X Egg",
                            PrecoUnitario = 4.50m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(1746),
                            Nome = "X Bacon",
                            PrecoUnitario = 7.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(1747),
                            Nome = "Batata frita",
                            PrecoUnitario = 2.00m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(1748),
                            Nome = "Refrigerante",
                            PrecoUnitario = 2.50m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DescontoPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("PromocaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Promocao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Promocao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d471"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(9291),
                            Nome = "Combo Completo",
                            Percentual = 0.20m
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d472"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(9296),
                            Nome = "Lanche e Refri",
                            Percentual = 0.15m
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 18, DateTimeKind.Utc).AddTicks(9298),
                            Nome = "Lanche e Batata",
                            Percentual = 0.10m
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PromocaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PromocaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromocaoId");

                    b.ToTable("PromocaoItens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d3c1f0-2e4b-4d9a-8c1f-5e7b2a6c9001"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1145),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d471"),
                            TipoItem = 1
                        },
                        new
                        {
                            Id = new Guid("b8e4d2a1-3c5f-4a8b-9d2e-6f1a3c7b9002"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1149),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d471"),
                            TipoItem = 3
                        },
                        new
                        {
                            Id = new Guid("c9f5e3b2-4d6a-4b7c-8e3f-7a2b4d8c9003"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1151),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d471"),
                            TipoItem = 2
                        },
                        new
                        {
                            Id = new Guid("e1b2c3d4-6f7a-4b8c-9d0e-8a1b2c3d4004"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1154),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d472"),
                            TipoItem = 1
                        },
                        new
                        {
                            Id = new Guid("f2c3d4e5-7a8b-4c9d-0e1f-9b2c3d4e5005"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1155),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d472"),
                            TipoItem = 3
                        },
                        new
                        {
                            Id = new Guid("a4d5e6f7-9b0c-4d1e-8f2a-2b3c4d5e6006"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1157),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            TipoItem = 1
                        },
                        new
                        {
                            Id = new Guid("b5e6f7a8-0c1d-4e2f-9a3b-3c4d5e6f7007"),
                            DataCriacao = new DateTime(2026, 5, 13, 0, 7, 30, 19, DateTimeKind.Utc).AddTicks(1158),
                            PromocaoId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d473"),
                            TipoItem = 2
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@goodhamburger.com",
                            Nome = "Administrador",
                            Perfil = 1,
                            SenhaHash = "$2a$11$xO.8W7K8G.kY6I6aD5g/2.QdY3k1s1uU0xXw0/A5b2O1e/wP7e5sC"
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.PromocaoItem", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.Promocao", null)
                        .WithMany("Requisitos")
                        .HasForeignKey("PromocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Promocao", b =>
                {
                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
